#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/scheduler-kubernetes/internal-functions"

case "$1" in
  help | scheduler-kubernetes:help)
    cmd-scheduler-kubernetes-help "$@"
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
