#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"

scheduler-kubernetes-install-dependencies() {
  declare desc="scheduler-kubernetes install-dependencies plugin trigger"
  declare trigger="scheduler-kubernetes-install-dependencies"

  case "$DOKKU_DISTRO" in
    debian | ubuntu)
      apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --force-yes -qq -y jq
      ;;

    opensuse)
      zypper -q in -y jq
      ;;

    arch)
      pacman -S --noconfirm --noprogressbar --needed jq
      ;;
  esac
}

scheduler-kubernetes-install-dependencies "$@"
