#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"

scheduler-kubernetes-install() {
  declare desc="scheduler-kubernetes install plugin trigger"
  declare trigger="scheduler-kubernetes-install"

  mkdir -p "${DOKKU_LIB_ROOT}/data/scheduler-kubernetes"
  chown -R "${DOKKU_SYSTEM_USER}:${DOKKU_SYSTEM_GROUP}" "${DOKKU_LIB_ROOT}/data/scheduler-kubernetes"

  fn-plugin-property-setup "scheduler-kubernetes"

  local KUBECTL_VENDOR_URL="${KUBECTL_VENDOR_URL:-"https://storage.googleapis.com"}"
  local KUBECTL_VERSION="${KUBECTL_VERSION:-v1.14.1}"
  if [[ ! -f "${DOKKU_LIB_ROOT}/data/scheduler-kubernetes/kubectl-${KUBECTL_VERSION}" ]]; then
    curl -L "${KUBECTL_VENDOR_URL}/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" -o "${DOKKU_LIB_ROOT}/data/scheduler-kubernetes/kubectl-${KUBECTL_VERSION}"
    cp "${DOKKU_LIB_ROOT}/data/scheduler-kubernetes/kubectl-${KUBECTL_VERSION}" "${DOKKU_LIB_ROOT}/data/scheduler-kubernetes/kubectl"
    chmod +x "${DOKKU_LIB_ROOT}/data/scheduler-kubernetes/kubectl"
  fi

  local KUBEDOG_VENDOR_URL="${KUBEDOG_VENDOR_URL:-"https://dl.bintray.com"}"
  local KUBEDOG_VERSION="${KUBEDOG_VERSION:-v0.2.0}"
  if [[ ! -f "${DOKKU_LIB_ROOT}/data/scheduler-kubernetes/kubedog-${KUBEDOG_VERSION}" ]]; then
    curl -L "${KUBEDOG_VENDOR_URL}/flant/kubedog/${KUBEDOG_VERSION}/kubedog-linux-amd64-${KUBEDOG_VERSION}" -o "${DOKKU_LIB_ROOT}/data/scheduler-kubernetes/kubedog-${KUBEDOG_VERSION}"
    cp "${DOKKU_LIB_ROOT}/data/scheduler-kubernetes/kubedog-${KUBEDOG_VERSION}" "${DOKKU_LIB_ROOT}/data/scheduler-kubernetes/kubedog"
    chmod +x "${DOKKU_LIB_ROOT}/data/scheduler-kubernetes/kubedog"
  fi

  if ! command -v jq &>/dev/null; then
    dokku_log_warn "This plugin script requires jq. Please call 'sudo dokku plugin:install-dependencies' to install this package."
  fi
}

scheduler-kubernetes-install "$@"
