#!/usr/bin/env bash
# Creates fake containerfile so ps:rebuild check for deployed app succeeds
# Hacky -- consider replacing with check for valid git repo

set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
source "$PLUGIN_AVAILABLE_PATH/scheduler-kubernetes/internal-functions"

scheduler-kubernetes-post-deploy() {
  declare desc="Creates fake containerfile to work around bug in ps:rebuild"
  declare trigger="scheduler-kubernetes-post-deploy"
  declare DOKKU_SCHEDULER="$1" APP="$2"

  if [[ "$DOKKU_SCHEDULER" != "kubernetes" ]]; then
    return
  fi

touch "$DOKKU_ROOT/$APP/CONTAINER.fakefile"
}

scheduler-kubernetes-post-deploy "$@"