#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"

scheduler-kubernetes-post-delete() {
  declare desc="scheduler-kubernetes post-delete plugin trigger"
  declare trigger="scheduler-kubernetes post-delete"
  declare APP="$1"

  local DOKKU_SCHEDULER=$(config_get "$APP" DOKKU_SCHEDULER || echo "docker-local")
  if [[ "$DOKKU_SCHEDULER" != "kubernetes" ]]; then
    return
  fi

  while read -r line || [[ -n "$line" ]]; do
    [[ "$line" =~ ^#.* ]] && continue
    line="$(strip_inline_comments "$line")"
    PROC_TYPE=${line%%=*}
    PROC_COUNT=${line#*=}

    if [[ "$PROC_TYPE" == "web" ]]; then
      "${DOKKU_LIB_ROOT}/data/scheduler-kubernetes/kubectl" delete service "${APP}-${PROC_TYPE}"
    fi
    "${DOKKU_LIB_ROOT}/data/scheduler-kubernetes/kubectl" delete deployment "${APP}-${PROC_TYPE}"
  done < "$DOKKU_SCALE_FILE"
}

scheduler-kubernetes-post-delete "$@"
