#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

scheduler-kubernetes-scheduler-tags-destroy() {
  declare desc="scheduler-kubernetes scheduler-tags-destroy plugin trigger"
  declare trigger="scheduler-kubernetes scheduler-tags-destroy"
  declare DOKKU_SCHEDULER="$1" APP="$2" IMAGE_REPO="$3" IMAGE_TAG="$4"

  if [[ "$DOKKU_SCHEDULER" != "kubernetes" ]]; then
    return
  fi

  dokku_log_warn "Not implemented for kubernetes"
}

scheduler-kubernetes-scheduler-tags-destroy "$@"
