#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

scheduler-kubernetes-scheduler-logs() {
  declare desc="scheduler-kubernetes scheduler-logs plugin trigger"
  declare trigger="scheduler-kubernetes scheduler-logs"
  declare DOKKU_SCHEDULER="$1" APP="$2" PROCESS_TYPE="$3" TAIL="$4" PRETTY_PRINT="$5" NUM="$6"
  shift 2

  if [[ "$DOKKU_SCHEDULER" != "kubernetes" ]]; then
    return
  fi

  local LABEL="app=${APP}"
  if [[ -n "$PROCESS_TYPE" ]]; then
    LABEL="app-process-type=${APP}-${PROCESS_TYPE}"
  fi

  local LOGS_ARGS="--tail $NUM"
  [[ "$TAIL" == "true" ]] && LOGS_ARG+=" --follow "
  "${DOKKU_LIB_ROOT}/data/scheduler-kubernetes/kubectl" logs -l "$LABEL"
}

scheduler-kubernetes-scheduler-logs-failed "$@"
