#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

scheduler-kubernetes-scheduler-logs-failed() {
  declare desc="scheduler-kubernetes scheduler-logs-failed plugin trigger"
  declare trigger="scheduler-kubernetes scheduler-logs-failed"
  declare DOKKU_SCHEDULER="$1" APP="$2"
  shift 2

  if [[ "$DOKKU_SCHEDULER" != "kubernetes" ]]; then
    return
  fi

  dokku_log_warn "Not implemented for kubernetes"
}

scheduler-kubernetes-scheduler-logs-failed "$@"
