#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

scheduler-kubernetes-scheduler-tags-create() {
  declare desc="scheduler-kubernetes scheduler-tags-create plugin trigger"
  declare trigger="scheduler-kubernetes scheduler-tags-create"
  declare DOKKU_SCHEDULER="$1" APP="$2" SOURCE_IMAGE="$3" TARGET_IMAGE="$4"
  shift 2

  if [[ "$DOKKU_SCHEDULER" != "kubernetes" ]]; then
    return
  fi

  dokku_log_warn "Not implemented for kubernetes"
}

scheduler-kubernetes-scheduler-tags-create "$@"
