#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
source "$PLUGIN_AVAILABLE_PATH/scheduler-kubernetes/internal-functions"

scheduler-kubernetes-scheduler-logs() {
  declare desc="scheduler-kubernetes scheduler-logs plugin trigger"
  declare trigger="scheduler-kubernetes scheduler-logs"
  declare DOKKU_SCHEDULER="$1" APP="$2" PROCESS_TYPE="$3" TAIL="$4" PRETTY_PRINT="$5" NUM="$6"
  local KUBE_ARGS NAMESPACE

  if [[ "$DOKKU_SCHEDULER" != "kubernetes" ]]; then
    return
  fi

  local LABEL="app=${APP}"
  if [[ -n "$PROCESS_TYPE" ]]; then
    LABEL="app-process-type=${APP}-${PROCESS_TYPE}"
  fi

  export KUBECONFIG="${DOKKU_ROOT}/.kube/config"
  export KUBEDOG_KUBE_CONFIG="${DOKKU_ROOT}/.kube/config"
  KUBE_ARGS=()
  NAMESPACE="$(fn-plugin-property-get "scheduler-kubernetes" "$APP" "namespace" "default")"
  KUBE_ARGS+=("--namespace=$NAMESPACE")
  fn-scheduler-kubernetes-ensure-namespace "$NAMESPACE" >/dev/null

  local LOG_ARGS="--tail $NUM"
  [[ "$TAIL" == "true" ]] && LOG_ARGS+=" --follow "
  "${DOKKU_LIB_ROOT}/data/scheduler-kubernetes/kubectl" "${KUBE_ARGS[@]}" logs -l "$LABEL" "${LOG_ARGS[@]}"
}

scheduler-kubernetes-scheduler-logs "$@"
