version: 2.1

commands:
  build:
    description: "run the build"
    parameters:
      python_version:
        type: string
        default: "3.7.0"
    steps:
      - checkout
      - run:
          name: resolve dokku.me
          command: |
            # dokku.me now resolves to 10.0.0.2. add 10.0.0.2/24 to ens4
            # this is maybe eth0 on github
            ifconfig
            sudo ip addr add 10.0.0.2/24 broadcast 10.0.0.255 dev ens4
      - run: pyenv global << parameters.python_version >>
      - run: make setup
      - run: sudo sysctl -w vm.max_map_count=262144
      # - run:
      #     command: |
      #       make generate
      #       if ! git diff --quiet README.md; then
      #         echo "Please run `make generate`"
      #         git status --short
      #         git --no-pager diff README.md
      #         exit 1
      #       fi
      - run: make test
      - store_artifacts:
          path: build
          destination: build
      - store_artifacts:
          path: tmp/test-results
          destination: test-results
      - store_test_results:
          path: tmp/test-results

executors:
  machine:
    machine:
      docker_layer_caching: false
      image: ubuntu-1604:201903-01

jobs:
  build-master:
    environment:
      DOKKU_VERSION: master
    executor: machine
    steps:
      - build

  build-version:
    environment:
      DOKKU_VERSION: v0.20.4
    executor: machine
    steps:
      - build

workflows:
  version: 2
  build:
    jobs:
      - "build-master"
      - "build-version"
