#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
source "$PLUGIN_AVAILABLE_PATH/scheduler-kubernetes/internal-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-scheduler-kubernetes-add-pvc() {
  declare desc="add a persistent volume claim"
  declare cmd="scheduler-kubernetes:add-pvc" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  while getopts name:access-modes:storage:storage-class-name:ns: option; do
    case "${option}" in
    name) NAME=${OPTARG} ;;
    access-modes) ACCESS_MODES=${OPTARG} ;;
    storage) STORAGE=${OPTARG} ;;
    storage-class-name) STORAGE_CLASS_NAME=${OPTARG} ;;
    ns) NAMESPACE=${OPTARG} ;;
    esac
  done
  [[ -z "$NAME" ]] && dokku_log_fail "Please specify a name for PVC"
  [[ -z "$ACCESS_MODES" ]] && dokku_log_fail "Please specify an access mode for PVC"
  [[ -z "$STORAGE" ]] && dokku_log_fail "Please specify storage size for PVC"
  [[ -z "$STORAGE_CLASS_NAME" ]] && dokku_log_fail "Please specify Storage class Name for PVC"
  
  fn-scheduler-kubernetes-add-pvc "$NAME" "$ACCESS_MODES" "$STORAGE" "$STORAGE_CLASS_NAME" "$NAMESPACE"
}

cmd-scheduler-kubernetes-add-pvc "$@"
