#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
source "$PLUGIN_AVAILABLE_PATH/scheduler-kubernetes/internal-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-scheduler-kubernetes-autoscale-rule-remove() {
  declare desc="remove an autoscale rule for an app/proc-type combination"
  declare cmd="scheduler-kubernetes:autoscale-rule-remove" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare APP="$1" PROC_TYPE="$2" RULE="$3"
  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  [[ -z "$RULE" ]] && dokku_log_fail "No rule specified"

  fn-scheduler-kubernetes-autoscale-rule-validate "$RULE"

  dokku_log_info2_quiet "Removing rule from ${PROC_TYPE}"
  fn-plugin-property-list-remove-by-prefix "scheduler-kubernetes" "$APP" "autoscale.$PROC_TYPE" "$RULE"
}

cmd-scheduler-kubernetes-autoscale-rule-remove "$@"
