#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
source "$PLUGIN_AVAILABLE_PATH/scheduler-kubernetes/internal-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-scheduler-kubernetes-list-mount() {
  declare desc="list mounted a volumes"
  declare cmd="scheduler-kubernetes:list-mount" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare APP="$1"
  [[ -z "$APP" ]] && dokku_log_fail "Please specify an App name"
  verify_app_name "$APP"

  dokku_log_info2_quiet "Listing Mounts as Claim-Name:Path"
  VOLUMES="$(fn-plugin-property-list-get "scheduler-kubernetes" "$APP" "volumes")"
  for VOLUME in "${VOLUMES[@]}"; do
    echo "$VOLUME"
  done
}

cmd-scheduler-kubernetes-list-mount "$@"
