#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
source "$PLUGIN_AVAILABLE_PATH/scheduler-kubernetes/internal-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-scheduler-kubernetes-remove-pvc() {
  declare desc="remove a persistent volume claim"
  declare cmd="scheduler-kubernetes:remove-pvc" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  while getopts ":-:" opt "$@"; do
    case "$opt" in
    -)
      case "$OPTARG" in
      name)
        val="${!OPTIND}"
        OPTIND=$((OPTIND + 1))
        local NAME="$val"
        ;;
      ns)
        val="${!OPTIND}"
        OPTIND=$((OPTIND + 1))
        local NAMESPACE="$val"
        ;;
      esac
      ;;
    esac
  done
  [[ -z "$NAME" ]] && dokku_log_fail "Please specify a name for PVC"
  [[ -z "$NAMESPACE" ]] && dokku_log_fail "Please specify Namespace for PVC"

  fn-scheduler-kubernetes-remove-pvc "$NAME" "$NAMESPACE"
}

cmd-scheduler-kubernetes-remove-pvc "$@"
