#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

scheduler-kubernetes-service-annotations-set-cmd() {
  declare desc="set or clear a scheduler-kubernetes service annotation for an app"
  local cmd="scheduler-kubernetes:service-annotations-set" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare APP="$1" KEY="$2" VALUE="$3"
  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  [[ -z "$KEY" ]] && dokku_log_fail "No key specified"

  if [[ -n "$VALUE" ]]; then
    dokku_log_info2_quiet "Setting ${KEY} to ${VALUE}"
    fn-plugin-property-list-add "scheduler-kubernetes" "$APP" "service-annotations" "$KEY $VALUE"
  else
    dokku_log_info2_quiet "Unsetting ${KEY}"
    fn-plugin-property-list-remove-by-prefix "scheduler-kubernetes" "$APP" "service-annotations" "$KEY"
  fi
}

scheduler-kubernetes-service-annotations-set-cmd "$@"
