#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-scheduler-kubernetes-set() {
  declare desc="set or clear a scheduler-kubernetes property for an app"
  declare cmd="scheduler-kubernetes:set" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare APP="$1" KEY="$2" VALUE="$3"
  local VALID_KEYS=("cert-manager-enabled" "imagePullSecrets" "ingress-enabled" "namespace" "pod-max-unavailable" "pod-min-available")
  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  [[ -z "$KEY" ]] && dokku_log_fail "No key specified"

  verify_app_name "$APP"
  if ! fn-in-array "$KEY" "${VALID_KEYS[@]}"; then
    dokku_log_fail "Invalid key specified, valid keys include: cert-manager-enabled, imagePullSecrets, ingress-enabled, namespace, pod-max-unavailable, pod-min-available"
  fi

  if [[ -n "$VALUE" ]]; then
    dokku_log_info2_quiet "Setting ${KEY} to ${VALUE}"
    fn-plugin-property-write "scheduler-kubernetes" "$APP" "$KEY" "$VALUE"
  else
    dokku_log_info2_quiet "Unsetting ${KEY}"
    fn-plugin-property-delete "scheduler-kubernetes" "$APP" "$KEY"
  fi
}

cmd-scheduler-kubernetes-set "$@"
