#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
source "$PLUGIN_AVAILABLE_PATH/scheduler-kubernetes/internal-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-scheduler-kubernetes-unmount-all() {
  declare desc="unmount all volumes"
  declare cmd="scheduler-kubernetes:unmount-all" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare APP="$1" && shift 1
  [[ -z "$APP" ]] && dokku_log_fail "Please specify an App name"
  verify_app_name "$APP"

  dokku_log_info2_quiet "unmounting all volumes from app (Re-Deploy Required) "
  fn-plugin-property-delete "scheduler-kubernetes" "$APP" "volumes"
}

cmd-scheduler-kubernetes-unmount-all "$@"
